# For full config options, check the docs:
#    v1.docs.serverless.com


service: tildeEOI # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3

# you can overwrite defaults here
defaults:
 stage: dev
 region: eu-west-1

# plugins:
#   - serverless-cors-plugin

package:
  exclude:
    - tmp
    - .git
    - front-end

functions:
  eoi:
    handler: index.eoi
    memorySize: 512
    timeout: 10
    events:
      - http:
          path: eoi/submit
          method: post

resources:
 Resources:
   newResource:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: tilde-submissions
